### PR TITLE
Clarify ObjectClassifier._select_features() behavior

### PR DESCRIPTION
**Pull request by kevinyamauchi**
Hello @haesleinhuepf . This PR adds a test and a slight docstring clarification related to #10 and #13. In fixing up the tests for #12 , I noticed that `ObjectClassifier._select_features()` returns two different numbers of features:

- When ground truth is provided, it returns n measurements for n labels
- When no ground truth is provided (e.g., when calling `ObjectClassifier.predict()`), it returns n+1 measurements for n features. That is background + 1 measurement per label

Is that the expected behavior? It works since there is code in `ObjectClassifier.predict()` to account for the additional measurement for the background ([here](https://github.com/haesleinhuepf/apoc/blob/32b84f86f73e7114e6ce7eb42571595e3e04e0b9/apoc/_object_classifier.py#L79-L80)). At some point, it might be nice to either create two separate functions or unify the behavior so the shape of the returned table is always the same.

### CODE REVIEW

**Review by haesleinhuepf — APPROVED** [review]
Hey @kevinyamauchi ,

I fully agree with the changes and can merge them right away. I'm just wondering if it wouldn't make sense to change the behaviour. IMO, we should not return measurements of background in general. Or do you see any use-case where background measurements are necessary?

Looking forward to hear your thoughts.

Greetings from Portugal :-)

**Comment by kevinyamauchi** [comment]
Hey @haesleinhuepf ! I agree that we should not return the background values from the classifier.

I think we can make the fix here:
https://github.com/haesleinhuepf/apoc/blob/34d10d597db2495e2dadfc07b955d2dc7647e1f0/apoc/_object_classifier.py#L196-L208

- for keys in `all_features`, we omit the `[0] + ` on line 197
- For the others, we can do `vector = np.asarray(calculation)[1:]

Does that sound right?

**Comment by haesleinhuepf** [comment]
> Is there an easy way to do that in `cle` or should we just use pyopencl?

I would do this with plain python. It's `[0] + list`, right?

**Comment by kevinyamauchi** [comment]
> I would do this with plain python. It's [0] + list, right?

We can definitely do this. I was hoping to avoid pulling and pushing the array from/to the GPU, but I imagine this will generally be a very small array, so it should be fine. I can implement that in this PR.

**Comment by haesleinhuepf** [comment]
> I can implement that in this PR.

That would be super cool. Thanks so much for working on this! :-)

**Pull request merged**
